# Generated by Django 3.1 on 2021-04-16 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineStatic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medName', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=1000)),
                ('firstname', models.CharField(max_length=1000)),
                ('dob', models.DateField()),
                ('weight', models.CharField(max_length=1000)),
                ('allergen1', models.CharField(blank=True, max_length=1000)),
                ('allergy1', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentApp.patient')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentApp.student')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medEdited', models.CharField(max_length=1000)),
                ('formDes', models.CharField(max_length=1000)),
                ('freDes', models.CharField(max_length=1000)),
                ('routeDes', models.CharField(max_length=1000)),
                ('doseDes', models.CharField(max_length=1000)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentApp.prescription')),
            ],
        ),
    ]
