# Generated by Django 3.2 on 2021-05-21 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markername', models.CharField(max_length=1000)),
                ('password', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineStatic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medName', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=1000)),
                ('firstname', models.CharField(max_length=1000)),
                ('dob', models.DateField()),
                ('weight', models.CharField(max_length=1000)),
                ('allergen1', models.CharField(blank=True, max_length=1000)),
                ('allergy1', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=1000)),
                ('password', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(blank=True)),
                ('review', models.TextField(blank=True)),
                ('lastname', models.CharField(max_length=1000)),
                ('firstname', models.CharField(max_length=1000)),
                ('dob', models.DateField(blank=True, max_length=1000)),
                ('weight', models.CharField(blank=True, max_length=1000)),
                ('allergen1', models.CharField(blank=True, max_length=1000)),
                ('allergy1', models.CharField(blank=True, max_length=1000)),
                ('student', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='studentApp.student')),
            ],
            options={
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='MedicineLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medEdited', models.CharField(blank=True, max_length=1000)),
                ('formDes', models.CharField(blank=True, max_length=1000)),
                ('freDes', models.CharField(blank=True, max_length=1000)),
                ('routeDes', models.CharField(blank=True, max_length=1000)),
                ('doseDes', models.CharField(blank=True, max_length=1000)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='studentApp.prescription')),
            ],
        ),
    ]
