# Generated by Django 3.2 on 2021-04-13 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=1000)),
                ('firstname', models.CharField(max_length=1000)),
                ('dob', models.DateField()),
                ('weight', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edited_weight', models.CharField(max_length=1000)),
                ('edited_allergy1', models.CharField(max_length=1000)),
                ('edited_allergy2', models.CharField(max_length=1000)),
                ('edited_allergy3', models.CharField(max_length=1000)),
                ('edited_allergy4', models.CharField(max_length=1000)),
                ('edited_allergy5', models.CharField(max_length=1000)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentApp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='PresMed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicineName', models.CharField(max_length=1000)),
                ('doseFreeText', models.CharField(max_length=1000)),
                ('form', models.CharField(max_length=1000)),
                ('route', models.CharField(max_length=1000)),
                ('frequency', models.CharField(max_length=1000)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentApp.prescription')),
            ],
        ),
        migrations.AddField(
            model_name='prescription',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentApp.student'),
        ),
    ]
