# Generated by Django 3.1.7 on 2021-04-28 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinelog',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='studentApp.prescription'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='studentApp.patient'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='review',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='studentApp.student'),
        ),
    ]
