# Generated by Django 3.1 on 2021-04-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=1000)),
                ('firstname', models.CharField(max_length=1000)),
                ('dob', models.DateField()),
                ('weight', models.CharField(max_length=1000)),
            ],
        ),
    ]
