# Generated by Django 3.2 on 2021-05-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='firstname',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='lastname',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
