# Generated by Django 3.1 on 2021-05-04 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0002_auto_20210505_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinelog',
            name='doseDes',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='medicinelog',
            name='formDes',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='medicinelog',
            name='freDes',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='medicinelog',
            name='medEdited',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='medicinelog',
            name='routeDes',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='studentApp.patient'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='student',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='studentApp.student'),
        ),
    ]
