# Generated by Django 3.1 on 2021-04-15 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0002_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('form', models.CharField(max_length=1000, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('frequency', models.CharField(max_length=1000, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineStatic',
            fields=[
                ('medName', models.CharField(max_length=1000, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('review', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PreToMedLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formDes', models.CharField(max_length=1000)),
                ('freDes', models.CharField(max_length=1000)),
                ('routeDes', models.CharField(max_length=1000)),
                ('doseDes', models.CharField(max_length=1000)),
                ('medStatic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentApp.medicinestatic')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentApp.prescription')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route', models.CharField(max_length=1000, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('uid', models.CharField(max_length=1000, primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Medicine',
        ),
        migrations.AddField(
            model_name='patient',
            name='allergen1',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='patient',
            name='allergy1',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentApp.patient'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentApp.student'),
        ),
        migrations.AddField(
            model_name='medicinestatic',
            name='pretomed',
            field=models.ManyToManyField(max_length=1000, through='studentApp.PreToMedLog', to='studentApp.Prescription'),
        ),
    ]
