# Generated by Django 3.1 on 2021-05-06 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0002_auto_20210428_1910'),
        ('studentApp', '0003_auto_20210505_0318'),
    ]

    operations = [
    ]
