# Generated by Django 3.1 on 2021-04-15 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0003_auto_20210415_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formDes', models.CharField(max_length=1000)),
                ('freDes', models.CharField(max_length=1000)),
                ('routeDes', models.CharField(max_length=1000)),
                ('doseDes', models.CharField(max_length=1000)),
                ('medEdited', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentApp.prescription')),
            ],
        ),
        migrations.RemoveField(
            model_name='medicinestatic',
            name='pretomed',
        ),
        migrations.DeleteModel(
            name='PreToMedLog',
        ),
    ]
