# Generated by Django 3.1 on 2021-05-06 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0004_merge_20210507_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='studentApp.patient'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='student',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='studentApp.student'),
        ),
    ]
