# Generated by Django 3.1 on 2021-04-15 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0004_auto_20210415_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinelog',
            name='prescription',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='studentApp.prescription'),
        ),
        migrations.AlterField(
            model_name='medicinelog',
            name='medEdited',
            field=models.CharField(max_length=1000),
        ),
    ]
