# Generated by Django 3.1 on 2021-04-15 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0005_auto_20210415_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinelog',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentApp.prescription'),
        ),
    ]
