# Generated by Django 3.1 on 2021-05-13 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0007_auto_20210511_1603'),
        ('studentApp', '0007_student_password'),
    ]

    operations = [
    ]
