# Generated by Django 3.1 on 2021-05-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0009_auto_20210513_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessorname', models.CharField(max_length=1000)),
                ('password', models.CharField(blank=True, max_length=1000)),
            ],
        ),
    ]
